
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.10.128:3307/teach?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enable: true
